---
name: Log-Log4perl-Layout-PatternLayout-Elapsed
version: 0.06
author:
  - 'Emmanuel Rodriguez, E<lt>emmanuel.rodriguez@gmail.comE<gt>.'
abstract: Logs the time elapsed between the last log event
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Log::Log4perl::Layout::PatternLayout: 0
build_requires:
  Log::Log4perl::Appender::TestBuffer: 0
  Test::More: 0
recommends:
  Time::HiRes: 0
dynamic_config: 0
provides:
  Log::Log4perl::Layout::PatternLayout::Elapsed:
    file: lib/Log/Log4perl/Layout/PatternLayout/Elapsed.pm
    version: 0.06
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
